### ISSUE TITLE
AttributeError for ScoreCAM Class

### ISSUE THREAD

**Issue by dwil2444** [jacobgil/pytorch-grad-cam#528] opened 2024-09-03 17:14 UTC
#### Description
I encountered an `AttributeError` when using the `ScoreCAM` class from the `pytorch_grad_cam` package. The error message is as follows:

`AttributeError: 'ScoreCAM' object has no attribute 'device'

  
#### Code Context 
In the ScoreCAM class, the line causing the error is:  
`activation_tensor = activation_tensor.to(self.device)`  

#### Expected Behavior
The ScoreCAM class should either:  

Initialize self.device properly, or
Avoid using self.device if it is not applicable.    

#### Possible Solution:  
One potential fix would be to pass device as a param to the constructor

#### Steps to Reproduce:  
Initialize a ScoreCAM object.
Call the object with

**Comment by jacobgil** [comment] 2024-09-04 05:56
Hi,
I can't reproduce this.
ScoreCAM inherits from BaseCAM which does have a self.device attribute.

Could you please share more information - which version are you using ?

**Comment by dwil2444** [comment] 2024-09-04 16:18
> Could you please share more information - which version are you using ?
Version 1.4.8

**Comment by jacobgil** [comment] 2024-09-04 19:02
This should be fixed in the latest releases. Could you please try upgrading the package ?

**Closed** 2024-09-27 19:02 UTC
