### ISSUE TITLE
Same feature map for Gradcam and Xgradcam

### ISSUE THREAD

**Issue by sumitmishra209** [jacobgil/pytorch-grad-cam#332] opened 2022-09-13 07:46 UTC
I was comparing the maps from different CAM and got Same feature map for Gradcam and Xgradcam. However this is not the case for Gradcam++. Anyone faced the same issue

**Comment by jacobgil** [comment] 2022-10-15 16:08
Hey,
I couldn't reproduce this issue.

If you can please provide more input, maybe the model and the image used, we can revisit it.

Closing for now.

**Closed by jacobgil** 2022-10-15 16:08 UTC
